### ISSUE TITLE
Translate all text in the local ar file

### ISSUE THREAD

**Issue by MuhannedNoman** [ReCoded-Org/capstone-IQLBPS-flashcard#118]
## Description

We can use google to create a quick translation, we just need to make sure things working.

## Steps to Reproduce
N/A

**Expected behavior:** 
Text changes to correct language

**Actual behavior:** 
Some text doesn't change.

**Comment by hayatzsala** [comment]
@MuhannedNoman should we merge this issue with this PR https://github.com/ReCoded-Org/capstone-IQLBPS-flashcard/pull/158?
