### ISSUE TITLE
Login Bug

### ISSUE THREAD

**Issue by reemshalak** [ReCoded-Org/capstone-IQLBPS-flashcard#127]
## Description

The User isn't redirected to the homepage if he enters the password  correctly for the second time.
## Steps to Reproduce

1. Enter a wrong password and press sign in
2. Enter the password again correctly and notice the issue.
3. Fix the routing problem

**Expected behavior:**  The User must be redirected upon entering the right info to the homepage

**Actual behavior:**  The User isn't redirected to the homepage after a  successful second attempt of entering a password.

**Comment by reemshalak** [comment]
Hello @Lelian248  , Can you check out this issue since you were working on the login functionality.

**Comment by Lelian248** [comment]
hi reem, yes i can fix that. if you notice anything else you can assign me
i don’t have any issues in my hand right now.
