### ISSUE TITLE
Personal Profile and Edit Profile issues

### ISSUE THREAD

**Issue by NijyarGS** [ReCoded-Org/capstone-IQLBPS-flashcard#150]
-Personal profile can not be accessed anywhere 
-when editing a profile uploading an image without changing the name will put change the username to Null
-Styling : Edit profile and personal profile image height and width are not uniform (they should have the same height and width).

**Comment by rch20** [comment]
@NijyarGS  I test the username thing and it's still working fine .

**Comment by reemshalak** [comment]
@NijyarGS  I tested the username thing and it works fine . 
I do agree about the other 2 issues.
