### ISSUE TITLE
Navbar Routing and User Info Render

### ISSUE THREAD

**Issue by reemshalak** [ReCoded-Org/capstone-IQLBPS-flashcard#166]
## Description

1. Navbar Profile dropdown should contain : Profile , Add Set , Sign Out
2. The username is appearing only when you refresh.
3.  Update profile image if image exists otherwise show default Image (user.photoURL not photourl)
## Steps to Reproduce

1.  Go to Navbar Component
2.  Locate the <Dropdown>
3. Fix the issues

**Expected behavior:**  when user clicks on image drop down appears with username-email : profile add set sign out working.

**Comment by NijyarGS** [comment]
fixed in #173
