### ISSUE TITLE
Change Website Logo to the newest one 

### ISSUE THREAD

**Issue by reemshalak** [ReCoded-Org/capstone-IQLBPS-flashcard#168]
## Summary

1. Change Logo in  the Navbar and Login- Sign Up Pages.
2. Change Login-Sign Up pages from flashcards to Cardly.
3. Fix the Login Page Don't have an account term .
### Screenshots

![logo2](https://user-images.githubusercontent.com/62399527/204106864-92af21e3-971d-428b-88f2-52bc05e8dc4b.png)

**Comment by hayatzsala** [comment]
@rch20 are we considering this logo for our website? since I used it in favicon need to be sure

**Comment by reemshalak** [comment]
@hayatzsala  Yes it is !!
